### ISSUE TITLE
Support multiple stacks

### ISSUE THREAD

**Issue by dougmoscrop** [dougmoscrop/serverless-plugin-bootstrap#7]
```yml
custom:
  bootstrap:
    - file: ...
    - file: ...
```
